name: Deployment Status

on:
  # This workflow can be triggered manually from the GitHub Actions tab
  workflow_dispatch:
    inputs:
      status:
        description: 'Deployment status'
        required: true
        default: 'success'
        type: choice
        options:
          - success
          - failure
          - in_progress
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: string
      description:
        description: 'Deployment description'
        required: false
        default: 'Coolify deployment'
        type: string

  # Can also be triggered by a webhook from Coolify
  repository_dispatch:
    types: [deployment-status]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update deployment status from manual trigger
        if: github.event_name == 'workflow_dispatch'
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.inputs.environment }}
          status: ${{ github.event.inputs.status }}
          deployment_id: ${{ github.run_id }}
          desc: ${{ github.event.inputs.description }}

      - name: Update deployment status from webhook
        if: github.event_name == 'repository_dispatch'
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.client_payload.environment || 'production' }}
          status: ${{ github.event.client_payload.status || 'success' }}
          deployment_id: ${{ github.event.client_payload.deployment_id || github.run_id }}
          desc: ${{ github.event.client_payload.description || 'Coolify deployment' }}
